FROM ubuntu

RUN apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y blt-dev 
RUN apt-get install -y bison flex gcc g++ make tk-dev xvfb

#copy everything in this folder to /omnet_workspace in virtual machine
WORKDIR /home/xterm
ADD . /home/xterm

#install omnet
ENV PATH "$PATH:/home/xterm/omnetpp-4.6/bin"
RUN cd omnetpp-4.6 && xvfb-run ./configure && make


